[package]
name = "cargo-license"
description = "Cargo subcommand to see license of dependencies"
authors = ["Onur Aslan <onur@onur.im>"]
version = "0.4.1"
license = "MIT"
readme = "README.md"
repository = "https://github.com/onur/cargo-license"
edition = "2018"

[dependencies]
getopts = "0.2.14"
toml = "0.4"
ansi_term = "0.9"
csv = "1"
serde = "1"
serde_derive = "1"
serde_json = "1.0"
cargo_metadata = "0.9.1"
semver = "0.9.0"
structopt = "0.3"
atty = "0.2"
anyhow = "1"
